### ISSUE TITLE
Enable importing of SBML models into Chaste

### ISSUE THREAD

**Issue by kwabenantim** [Chaste/Chaste#134]
## Background
* [SBML](https://synonym.caltech.edu) and [CellML](https://www.cellml.org) are now widely adopted for defining and sharing models of subcellular biological processes.
* @MauriceHendrix  and @mirams  have developed [chaste-codegen](https://github.com/ModellingWebLab/chaste-codegen) as a Python 3 replacement for Chaste’s CellML-to-Chaste-C++ converter.
* Other preliminary work by @jmosborne has investigated using [libSBML](https://synonym.caltech.edu/software/libsbml/) to parse SBML files and create Chaste-compatible C++ classes specifying subcellular reaction networks ([SBMLChaste](https://github.com/jmosborne/SBMLChaste)).

## Scope of Work
Building on these efforts, we will:
* Extend the primary Chaste codebase to enable all users to import new/existing SBML models for gene regulatory networks and signalling pathways.
* Seek to validate these SBML capabilities through external compliance testing (https://synonym.caltech.edu/software/sbml-test-suite).

## Test Results

[ [docs.google.com/spreadsheets/d/1SpM8Cs7RcQ6rHxWGf2YZ68y2WrCjqH5ZRUFE-CGdQmU](https://docs.google.com/spreadsheets/d/1SpM8Cs7RcQ6rHxWGf2YZ68y2WrCjqH5ZRUFE-CGdQmU/edit?gid=1619637506#gid=1619637506) ]

🟩🟩🟩🟩🟩🟩🟥🟩🟩🟩🟩🟩🟩🟦🟩🟩🟩🟩🟩🟩
🟩🟩🟥🟩🟩🟩🟩🟩🟩🟩🟩🟩🟩🟩🟩🟩🟩🟦🟩🟩

## See Also
* Trac archive: [Sbml-Sub-Cellular-Models](https://github.com/Chaste/trac_archive/wiki/Sbml-Sub-Cellular-Models)
* Trac archive: [Sbml-Translator](https://github.com/Chaste/trac_archive/wiki/Sbml-Translator)

**Comment by kwabenantim** [comment]
## Roadmap
- [x] SRN Models
  - [x] Start with existing code from [SBMLChaste](https://github.com/jmosborne/SBMLChaste).
    - [x] Check that existing code works with current Chaste `develop`.
    - [x] Check that existing code generator works with Python 3.
  - [x] No cell-cell communication:
    - [x] Generate C++ Chaste code for simpler models that do not need cell-cell coupling e.g. Goldbeter (1991).
    - [x] Add tests to check that generated model matches expected model.
    - [x] Check that generated models pass existing Chaste tests.
  - [x] Cell-cell communication:
    - [x] Generate C++ Chaste code for models that require cell-cell coupling e.g. Van Leeuwen (2007).
    - [x] Add tests to check that generated model matches expected model.
    - [x] Check that generated models pass existing Chaste tests.
- [x] Cell-Cycle Models
  - [x] Generate cell-cycle models from SBML for models that already exist in Chaste e.g. WntCellCycleModel.
    - [x] Work out how to handle events (this isn't a consideration for SRN models).
      - [x] Try using CVODE root finding to look for ODE events e.g. cell size drops to 0.
  - [x] Add tests to check that generated model matches expected model.
  - [x] Check that generated models pass existing Chaste tests.
- [x] Project
  - [x] Create a separate [chaste_codegen_sbml](https://github.com/Chaste/chaste-codegen-sbml) project.
  - [x] Pin specific versions of `libSBML` and other  dependencies.
  - [x] Use similar test setup as `chaste_codegen` i.e. use CMake to create a virtualenv etc.
    - [x] ~~Use same virtualenv as `chaste_codegen` to avoid slowing down configuration.~~ (Not installed in Chaste config).
    - [x] ~~Consider merging `chaste_codegen_sbml` and `chaste_codegen` into same package, perhaps one package with two submodules, one for cellml and the other for sbml.~~ (No merge).
  - [x] ~~Allow Chaste run-time / compile-time code generation from Chaste, similar to approach used in `chaste_codegen`.~~ (Use in user projects).
  
### Other
- [ ] Update https://en.wikipedia.org/wiki/List_of_systems_biology_modeling_software

**Comment by kwabenantim** [comment]
## Goldbeter (1991)
* Paper: [A minimal cascade model for the mitotic oscillator involving cyclin and cdc2 kinase](https://doi.org/10.1073/pnas.88.20.9107)
* SBML: https://www.ebi.ac.uk/biomodels/BIOMD0000000003
* Chaste Implementation:
  * Goldbeter1991OdeSystem [cpp](https://github.com/Chaste/Chaste/blob/develop/cell_based/src/odes/Goldbeter1991OdeSystem.cpp) [hpp](https://github.com/Chaste/Chaste/blob/develop/cell_based/src/odes/Goldbeter1991OdeSystem.hpp)
  * Goldbeter1991SrnModel [cpp](https://github.com/Chaste/Chaste/blob/develop/cell_based/src/cell/srn/Goldbeter1991SrnModel.cpp) [hpp](https://github.com/Chaste/Chaste/blob/develop/cell_based/src/cell/srn/Goldbeter1991SrnModel.hpp)

### Notes
* Chaste C++ model was generated successfully from SBML using SBMLChaste.
* There are some differences in implementation between the generated model and the existing Chaste model.
* Current tests do not work for generated model due to implementation differences. For example:
  * Missing expected `GetC()`, `GetM()`, and `GetX()` methods to return state variables.
  * OdeSystem and SrnModel are combined in a single file in the generated model but separated in the original Chaste implementation.
  * Some code that needs fixing e.g. `double activation of cdc2 kinase = cell * (1 + -1 * CDC-2 Kinase) * V1 * pow(K1 + -1 * CDC-2 Kinase + 1, -1);`

### Tests
- [x] TestGoldbeter1991CellSrn
   - Fix variable names.
  - Fix generated ODE number of parameters from 5 to 3.
  - Add methods to get state variables. Use variable names for clarity.
  - Disable "timescale conversions".
  - SetDt(0.1)
  - Use the `RungeKutta4IvpOdeSolver` solver, same as the existing class.
- [x] TestGoldbeter1991OdeSystem
- [x] TestGoldbeter1991OdeBasedSrnModels
  - Model identifier is "SbmlSrnWrapperModel-GoldbeterOdeSystem-3".

**Comment by mirams** [comment]
I would think `GetM()` etc. methods should be replaced by ones that follow the OdeSystemInformation form, e.g. `GetVariable("M")` or `GetParameter("M")` etc. (automatically available when OdeSystemInformation in the hpp is complete.)

**Comment by mirams** [comment]
Work is in a separate [chaste_codegen_sbml](https://github.com/Chaste/chaste-codegen-sbml) project.
