### ISSUE TITLE
September workshop organisation

### ISSUE THREAD

**Issue by fcooper8472** [Chaste/Chaste#140]
Some associated tasks/issues it would be good to have done before the workshop:

- [x] Once the workshop webpage and application form are finalised, advertise the workshop via:
    - [x] the SMB digest;
    - [x] the Node;
    - [x] direct emails to relevant math/comp bio groups:
        - [x] Aberdeen
        - [x] Bath
        - [x] Birmingham
        - [x] Bristol
        - [x] Cambridge
        - [x] Cardiff
        - [x] Dundee
        - [x] Durham
        - [x] Edinburgh
        - [x] Exeter
        - [x] Glasgow
        - [x] Imperial
        - [x] KCL / Crick Institute
        - [x] Leeds
        - [x] Liverpool
        - [x] Manchester
        - [x] Nottingham
        - [x] Oxford - Math Bio
        - [x] Oxford - Comp Bio
        - [x] Sheffield
        - [x] Southampton
        - [x] St Andrews
        - [x] Sussex
        - [x] Swansea
        - [x] Warwick
        - [x] York
    - [x] any other mailing lists people can think of (is there an RSE one?).
        - [x] Old Chaste mail list 
- [ ] Finish migration to GitHub (#35)
- [ ] Migrate CI to GitHub actions (#38)
- [ ] Move main Chaste website (#39)
- [x] Create a Chaste forum for user support (#42)
- [ ] Get Docker support for apple m series processors (#43)
- [ ] Migrate remaining BuildBot tasks to GitHub (#50)
- [ ] Migrate tutorial generation from buildbot to github actions (#55)
- [x] Create private Chaste repo with associated wiki (#59)
- [x] Implement Python wrappers for cell-based simulations (#60)
- [ ] Get ready for (and make) a new release (#125)
- [ ] Chaste docker: Automating multi-architecture build through GitHub actions (#136)
- [ ] Modernise use of C++(#139)
- [x] Allocate responsibility for preparing [workshop tutorials](https://chaste.github.io/workshops/2023-09-11/)
- [ ] Logistics (food/drink/accommodation)
- [ ] Share who has applied

**Comment by AlexFletcher** [comment]
Barcelona workshop practicals: https://colab.research.google.com/drive/1apBYkUNkBL5GU6jQ9Ocag7jRFNiHieJx

**Comment by MILeach** [comment]
## Workshop tutorial responsibility

### Monday
- Intro to vertex models etc - Alex 
- Using PyChaste - Alex 
- Material for these already prepared

### Tuesday
- Using C++ interface to make more substantial changes - Fergus
- New functionality i.e. immersed boundary - Matt
- Overview of chaste infrastructure - Joe
- Intro to RSE - Kwabena, also reaching out to Dave & Martin

### Wednesday
- Coupling cell & microenvironment - Alex & Jack
- Cell environment feedback - Alex & Jack

**Comment by BJackal** [comment]
- @MILeach   and other developers will decide on a strategy for where jupytr notebookes/ google collab sheets will be stored and with a view to have these available by the 28th of August.
- Ask additional speakers to take part in the workshop.
- All developers to sign up for the workshop.
-  @kwabenantim will also give a talk on the workings of PyChaste and how pybind is used.

**Comment by BJackal** [comment]
@BJackal 2 short tutorial on Delta-notch and Planar polarity to be developed for end of August. Possible discussion of state reaction network models to link in with earlier talks.

**Comment by MILeach** [comment]
@MILeach to set up info repository by lunchtime on Wed 30th August for workshop notebooks & populate readme with a timetable. One central repo with all information, can link out to other repos as necessary.

**Comment by fcooper8472** [comment]
Workshop has happened!
