### ISSUE TITLE
Create GitHub runner docker images for newer Ubuntus

### ISSUE THREAD

**Issue by kwabenantim** [Chaste/Chaste#197]
**Summary**
Create  images with dependency versions for:
* ~~[Ubuntu 22.10](https://packages.ubuntu.com/kinetic/) Kinetic Kudu~~ [End of Life](https://fridge.ubuntu.com/2023/06/14/ubuntu-22-10-kinetic-kudu-reaches-end-of-life-on-july-20-2023/)
* [Ubuntu 23.04](https://packages.ubuntu.com/lunar/)  Lunar Lobster
* [Ubuntu 23.10](https://packages.ubuntu.com/mantic/) Mantic Minotaur

**Tasks**
- [x] ~~Build docker image for `chaste/runner:kinetic.portability-dev`.~~
- [x] Build docker image for `chaste/runner:lunar.portability-dev`.
- [x] Build docker image for `chaste/runner:mantic.portability-dev`.
- [x] Modify boost modulefiles in old portability images to set `FindBoost.cmake` variables. 
- [x] Fix workflows to use `FindBoost.cmake` variables from modulefiles. 
- [x] Write developer documentation on building and testing new dependency versions (https://github.com/Chaste/developer_wiki/wiki/Portability-Testing)
- [x] Fix `cvector` errors.

**PRs**
* #205 
* https://github.com/Chaste/dependency-modules/pull/60
* https://github.com/Chaste/dependency-modules/pull/61
* https://github.com/Chaste/dependency-modules/pull/62
* https://github.com/Chaste/dependency-modules/pull/63

**Related Issues**
* #198

**Comment by kwabenantim** [comment]
Currently, system images don't configure correctly because `-DBoost_NO_BOOST_CMAKE` and `-DBoost_NO_SYSTEM_PATHS` are set directly in CI workflows. Moving the options into the modulefiles will allow images to set them `ON` and `OFF` as required.

**Comment by kwabenantim** [comment]
Getting `maybe-uninitialized` errors with GCC 13.2.0 on Ubuntu 23.10 Mantic Minotaur: https://github.com/Chaste/dependency-modules/actions/runs/7539367160/job/20521728238

**Comment by mirams** [comment]
Worth a look to see if the compiler is correct, sometimes it is and sometimes it isn't for these sort of warnings. Probably don't want to disable that warning globally anyway, it is a useful one!

**Comment by kwabenantim** [comment]
> Getting `maybe-uninitialized` errors with GCC 13.2.0 on Ubuntu 23.10 Mantic Minotaur: https://github.com/Chaste/dependency-modules/actions/runs/7539367160/job/20521728238

~~Fixed after rebuilding image with boost modulefile changes.~~

**Comment by kwabenantim** [comment]
> Worth a look to see if the compiler is correct, sometimes it is and sometimes it isn't for these sort of warnings. Probably don't want to disable that warning globally anyway, it is a useful one!

Thanks @mirams. It is probably an issue with boost configuration in this case.

**Comment by kwabenantim** [comment]
It turns out boost is configuring properly. The same error occurs in the base Ubuntu 23.10 Mantic Minotaur image without the modulefiles.

**Comment by kwabenantim** [comment]
All portabilities pass except for the new ones - Lunar (gcc 12) and Mantic (gcc 13).

The configure step completes okay, but the build step throws `maybe-uninitialized` errors.

https://github.com/Chaste/Chaste/actions/runs/7623994326

**Comment by MILeach** [comment]
@fcooper8472 to investigate c vector errors
