### ISSUE TITLE
Support PETSc 3.21 - 3.22

### ISSUE THREAD

**Issue by mirams** [Chaste/Chaste#327]
**Changes here:**
* https://petsc.org/release/changes/321/
* https://petsc.org/release/changes/322/

**TODO**

- [x]  Make new portability images for testing (https://github.com/Chaste/dependency-modules)
- [x]  See if `develop` builds and passes all tests
- [x]  Do any necessary fixes
  - [x] `TestCitations`
  - [x] `TestPetscTools`
  - [x] `TestChebyshevIteration`
  - [x] `TestLinearSystem`
  - [x] `TestPCBlockDiagonal`
  - [x] `TestPCLDUFactorisation`
  - [x] `TestPCTwoLevelsBlockDiagonal`
  - [x] `TestCardiacElectroMechanicsProblemLong`
- [x]  Add portability images to testing rotation
- [x] Update portability rotation table: https://github.com/Chaste/developer_wiki/wiki/Portability-Testing-Guide
- [x]  Update supported dependency versions page: https://chaste.github.io/docs/installguides/dependency-versions/

**Comment by kwabenantim** [comment]
A portability test with PETSc 3.22 has been added on PR #328 

[Currently failing tests](https://github.com/Chaste/Chaste/actions/runs/11240526716/job/31250062855?pr=328):

```
The following tests FAILED:
Errors while running CTest
	  3 - TestCitations (Failed)
	 28 - TestPetscTools (Failed)
	 56 - TestChebyshevIteration (Failed)
	 58 - TestLinearSystem (Failed)
	 62 - TestPCBlockDiagonal (Failed)
	 63 - TestPCLDUFactorisation (Failed)
	 64 - TestPCTwoLevelsBlockDiagonal (Failed)
```

**Comment by kwabenantim** [comment]
Currently tested with these [portabilities](https://hub.docker.com/r/chaste/runner/tags):
* `portability-04` has PETSc 3.21
* `portability-dev` has PETSc 3.22

**Comment by kwabenantim** [comment]
Sorry, my fault for not clarifying. It needs a bit more work to correct the failing tests.

**Comment by mirams** [comment]
Oh, when you requested review I thought it was to switch on the portabilities!

**Comment by kwabenantim** [comment]
**Passing tests**
```
TestCitations
```

**Failing tests** ([3.21](https://github.com/Chaste/Chaste/actions/runs/13369259798/job/37333932889) and [3.22](https://github.com/Chaste/Chaste/actions/runs/13369259798/job/37333936116)):
```
TestPetscTools (Failed)
TestChebyshevIteration (Failed)
TestLinearSystem (Failed)
TestPCBlockDiagonal (Failed)
TestPCLDUFactorisation (Failed)
TestPCTwoLevelsBlockDiagonal (Failed)
```

**Comment by kwabenantim** [comment]
I've added some notes on setting up a portability Codespace on PR #383

**Comment by jmpf** [comment]
All remaining failing tests: 
`TestPetscTools 
TestChebyshevIteration 
TestLinearSystem 
TestPCBlockDiagonal 
TestPCLDUFactorisation 
TestPCTwoLevelsBlockDiagonal` fall over in `PetscTools::ChasteMatCopy`, so may be manifesting the same bug.

**Comment by jmpf** [comment]
Failing tests are caused by [0b963dc](https://github.com/Chaste/Chaste/commit/0b963dc9627325242d335c49810c4e0124cb7478#diff-f8cc1135b2e73d2bfbc4554f9d2b0dd2b1647dbca4b587cf11d1d7a1f2ec7f0f)
Perhaps @fcooper8472 can recall why this code was used as a "temporary fix"?  Are there some notes somewhere?

**Comment by jmpf** [comment]
"Temporary fix" to solve runtime failures with [PETSc 3.11](https://github.com/Chaste/trac_archive/blob/master/issues/3021.md) can probably be solved in a much slicker manner.

To read a matrix with a non-default parallel layout, the code from PETSc 3.1 onward reads first into the default layout, and then into a non-default layout.  It's possible in more modern PETSc (at least 3.15) to read the matrix directly into the non-default layout.

**Comment by jmpf** [comment]
Ability to read matrix into arbitrary parallel structure may have come as early as [release 3.2](https://petsc.org/release/changes/32/) but, if not, was probably in [release 3.11](https://petsc.org/release/changes/311/).

**Comment by jmpf** [comment]
Code for modern PETSc - before I have to rewrite it with caveats for different versions
```
void PetscTools::ReadPetscObject(Mat& rMat, const std::string& rOutputFileFullPath, Vec rParallelLayout)
{
    PetscViewer view;
    PetscFileMode type = FILE_MODE_READ;
    PetscViewerBinaryOpen(PETSC_COMM_WORLD, rOutputFileFullPath.c_str(),
                          type, &view);

    if (rParallelLayout != nullptr)
    {
        PetscInt num_rows, num_local_rows;
        VecGetSize(rParallelLayout, &num_rows);
        VecGetLocalSize(rParallelLayout, &num_local_rows);       
        /// \todo: #1082 work out appropriate nz allocation.
        PetscTools::SetupMat(rMat, num_rows, num_rows, 100, num_local_rows, num_local_rows, false);

    }
    else
    {
        MatCreate(PETSC_COMM_WORLD, &rMat);
        MatSetType(rMat, MATMPIAIJ);   
    }
    MatLoad(rMat, view);

    PetscViewerDestroy(PETSC_DESTROY_PARAM(view));
}
```

**Comment by jmpf** [comment]
Commits mentioned above fix all failing tests on PETSc 3.21.6 according to Codespace  VM.  Pull request has some failures, but these are probably not related to the PETSc fix.

**Comment by kwabenantim** [comment]
`TestLinearSystem` [fails in coverage](https://github.com/Chaste/Chaste/actions/runs/14222508042/job/39853841373) because coverage runs in an older image with PETSc 3.8, which is no longer supported. I'll update coverage to use the [portability-01](https://github.com/Chaste/developer_wiki/wiki/Portability-Testing-Guide#portability-rotation) image which has PETSc 3.14.

Better still, I'll tag the `portability-01` image as `coverage-runner` so we can move the tag to another image in the future without editing the GitHub actions coverage workflow.

Does this seem sensible to you @fcooper8472 ?

**Comment by jmpf** [comment]
I see @kwabenantim has added TestCardiacElectroMechanicsProblemLong.  I am not sure under what circumstances this test is supposed to pass.  (I remember it being quite a fragile test.)  It crashes when using PETSc 3.15.5 (with DEBUG build).  Can anyone point me to a CI test where it passes?

**Comment by jmpf** [comment]
Confirmed that this test is working with [portability-jammy](https://github.com/Chaste/Chaste/actions/runs/14297232560/job/40065948476) which is configured with PETSc 3.15.5.  It also works with later PETSc versions...

**Comment by jmpf** [comment]
> Confirmed that this test is working with [portability-jammy](https://github.com/Chaste/Chaste/actions/runs/14297232560/job/40065948476) which is configured with PETSc 3.15.5. It also works with later PETSc versions...

Unfortunately I still cannot replicate this test suite passing on Jammy:
```
cmake .. -DCMAKE_BUILD_TYPE=Release
make TestChasteBuildInfo TestCardiacElectroMechanicsProblemLong
$ ./global/test/TestChasteBuildInfo 
Running 1 test
Changing directory from '/home/jmpf/Workspace/Chaste/build/' to '/home/jmpf/Workspace/Chaste/'.
CWD now: /home/jmpf/Workspace/Chaste


 ***** TestChasteBuildInfo.hpp *****


Entering TestShowInfo
<ChasteBuildInfo>
	<ProvenanceInfo>
		<VersionString>2024.2.43b116b</VersionString> <!-- build specific -->
		<IsWorkingCopyModified>1</IsWorkingCopyModified>
		<BuildInformation>Release</BuildInformation>
		<BuildTime>Wed, 16 Apr 2025 13:06:24 +0000</BuildTime>
		<CurrentTime>Wed, 16 Apr 2025 15:03:17 +0000</CurrentTime>
		<BuilderUnameInfo>Linux</BuilderUnameInfo>
		<ChasteTestOutputDirectory>/home/jmpf/Workspace/Chaste/build/testoutput/</ChasteTestOutputDirectory>
		<Projects>
		</Projects>
	</ProvenanceInfo>
	<Compiler>
		<NameAndVersion>/usr/bin/c++, version 11.4.0</NameAndVersion>
		<Flags>-Wall -Werror -Wnon-virtual-dtor -Woverloaded-virtual -Wextra -Wno-attributes -Wno-unused-parameter -Wvla -Wimplicit-fallthrough=2 -Wno-maybe-uninitialized -Wno-array-bounds -Wno-stringop-overflow -Wno-stringop-overread -O3 -DNDEBUG</Flags>
	</Compiler>
	<Libraries>
		<CompiledIn>
			<PETSc>3.15.5</PETSc>
			<Boost>1.74.0</Boost>
			<HDF5>1.10.7</HDF5>
			<Parmetis>4.0.3</Parmetis>
		</CompiledIn>
		<Binaries>
			<XSD>4.0.0</XSD>
		</Binaries>
		<Optional>
			<SUNDIALS>5.8.0</SUNDIALS>
			<VTK>7.1</VTK>
			<Xerces>3.2.3</Xerces>
		</Optional>
	</Libraries>
	<ChasteCodegenVersion>chaste_codegen 0.10.6</ChasteCodegenVersion>
</ChasteBuildInfo>
Passed
OK!

```

Note that this build info is almost identical to `portability-jammy` I referenced above but I get this failure:
```
 ***** TestCardiacElectroMechanicsProblemLong.hpp *****


Entering Test2dHardcodedResult
       Assemble            Solve           Update          AllMech          NonMech           Output            Total  
   0.618 (  5%)     1.062 (  8%)     0.713 (  6%)     2.506 ( 20%)     9.950 ( 79%)     0.018 (  0%)    12.524 (100%)  (seconds) 
Passed
Entering Test2dVariableFibres
terminate called after throwing an instance of 'Exception'
  what():  
Chaste error: ./continuum_mechanics/src/solver/AbstractNonlinearElasticitySolver.hpp:1968: Residual does not appear to decrease in newton direction, quitting

```

**Comment by mirams** [comment]
See also #405 for next version of PETSc

**Comment by jmpf** [comment]
I'm convinced that `TestCardiacElectroMechanicsProblemLong` failures are not specific to PETSc 3.21 etc.  I have altered the #380 PR to make the test a bit less fragile.

**Comment by jmpf** [comment]
`TestCardiacElectroMechanicsProblemLong` failure was most probably unrelated, but sufficiently fragile for a change in PETSc implementation to hurt it.
