### ISSUE TITLE
Migrate CI to GitHub actions

### ISSUE THREAD

**Issue by kwabenantim** [Chaste/Chaste#38]
This issue continues the discussion for legacy trac ticket 3099:
___

[fcooper8472](https://github.com/orgs/Chaste/people/fcooper8472) created the following ticket on 2022-05-20 at 11:11:57, it is owned by [fcooper8472](https://github.com/orgs/Chaste/people/fcooper8472)

---
Comment by [kwabenantim](https://github.com/orgs/Chaste/people/kwabenantim) on 2022-08-25 at 10:33:09

Portability Testing:

* I've added some scripts in the Chaste [dependency-modules](https://github.com/Chaste/dependency-modules) repository for installing dependency versions as [Environment Modules](https://modules.readthedocs.io/en/latest/) so that we can have multiple versions side-by-side and switch between them for testing Chaste.
* The dependency-modules repo also contains scripts for building a Docker image to use as a [self-hosted](https://docs.github.com/en/actions/hosting-your-own-runners/about-self-hosted-runners) github actions runner, based on Ubuntu 20.04.
* I've added some documentation on the wiki ~~???~~ about setting up the runner, and for [developers](https://chaste.cs.ox.ac.uk/trac/wiki/ChasteGuides/ModulesSetupGuide) who want to test Chaste with multiple versions of dependencies.
* The next step is to shadow the current portability tests and fix any issues that may occur.

---
Comment by [kwabenantim](https://github.com/orgs/Chaste/people/kwabenantim) on 2022-08-25 at 13:15:46

Portability Testing:

* Built and pushed the github actions runner image to docker hub as chaste/runner <https://hub.docker.com/r/chaste/runner>
* Updated documentation on the wiki to use the chaste/runner image from docker hub.

---
Comment by [kwabenantim](https://github.com/orgs/Chaste/people/kwabenantim) on 2022-09-01 at 08:13:01

Portability Testing

- Added a new GH Actions workflow to automatically build and push the chaste/docker image to dockerhub when a new release is published on the repository:
    - https://github.com/Chaste/dependency-modules/blob/main/.github/workflows/docker-release.yml
- Added daily cron jobs to the GH Actions portability workflow with different versions of dependencies for each weekday.
    - "Old" versions are based on Ubuntu 18.04.
    - "New" versions are based on Ubuntu 22.04.
    - "Bleeding Edge" versions are the latest for the dependencies.
    - Jobs can compile Chaste without VTK and Sundials.
    - https://github.com/Chaste/dependency-modules/pull/30
- I'm monitoring the daily job runs for issues.

**Comment by fcooper8472** [comment]
Work on this issue is not yet complete, but the vast majority of the useful CI is now working.  My plan is to merge the current state of the CI branch into develop this afternoon, and then update this issue with the remaining tasks.

This will then allow all open PRs to merge develop in, and get the benefit of CI running on the PRs which will help get the pipeline for merging working as intended.

**Comment by mirams** [comment]
This is another piece of magic that it would be nice to keep. I refer to it quite often:
https://chaste.cs.ox.ac.uk/trac/wiki/ChasteGuides/HowTo
(comments matching HOW_TO in the code make this wiki page automatically)

**Comment by fcooper8472** [comment]
The open tasks on this umbrella issue are:

- [x] doxygen (#160) and doxygen coverage (#179)
- [x] tutorial generation (#55)
- [ ] finish porting public web pages (#39)
- [x] generate how-to page (#185)

**Comment by fcooper8472** [comment]
I'm closing this now; the only outstanding issue is #39 which contains all the remaining website-related jobs.
