### ISSUE TITLE
Implement Python wrappers for cell-based simulations

### ISSUE THREAD

**Issue by kwabenantim** [Chaste/Chaste#60]
This issue continues the discussion for legacy trac ticket 3104:
___
[kwabenantim](https://github.com/orgs/Chaste/people/kwabenantim) created the following ticket on 2022-09-02 at 11:33:49, it is owned by [kwabenantim](https://github.com/orgs/Chaste/people/kwabenantim)* 

For those without C++ expertise, implementation of higher-level programming language bindings would offer a step change in Chaste’s usability. Extending on preliminary work in [legacy ticket 2686] on [PyChaste](https://github.com/jmsgrogan/PyChaste/), we will use [PyBind11](https://pybind11.readthedocs.io) to generate Python wrappers for cell-based Chaste.

**Comment by kwabenantim** [comment]
Building a conda package for PyChaste that works with [develop](/Chaste/Chaste/tree/develop).

So far, a manual build with these versions of dependencies from [conda-forge](https://anaconda.org/conda-forge/repo) and [bioconda](https://anaconda.org/bioconda/repo) works:
```
  - python >=3.7
  - vtk ==8.2.0
  - tbb ==2019.9
  - tbb-devel ==2019.9
  - boost ==1.74.0
  - petsc ==3.10.5
  - petsc4py ==3.10.0
  - hdf5 =1.10.5=mpi_mpich_*
  - parmetis ==4.0.3
  - sundials ==5.0.0
  - xsd
  - xerces-c ==3.2.4
 ```
 
Note: the [vtk](https://anaconda.org/conda-forge/vtk) builds from conda-forge depend on [tbb](https://anaconda.org/conda-forge/tbb), not [mpi](https://anaconda.org/conda-forge/mpi).

Trying to get [conda-build](https://anaconda.org/conda-forge/conda-build) to make the conda package.

**Comment by kwabenantim** [comment]
The conda package was built with [conda mambabuild](https://github.com/mamba-org/boa) and is now up on a [test channel](https://anaconda.org/kwabenantim/chaste). Currently testing it in a Jupyter notebook and fixing issues.

To install, run:
`conda install -c kwabenantim chaste`

To start a Jupyter notebook, run:
`jupyter notebook`

**Comment by kwabenantim** [comment]
Test | Status
-- | --
ode/TestOdeSystemPython.py | passing
cell_based/tutorials/TestScratchAssayTutorial.py | passing
cell_based/tutorials/TestVertexBasedCellSimulationsPythonTutorial.py | failing
cell_based/tutorials/TestMeshBasedCellSimulationsPythonTutorial.py | passing
cell_based/tutorials/TestPottsBasedCellSimulationsPythonTutorial.py | passing
cell_based/tutorials/TestSpheroidTutorial.py | passing
cell_based/tutorials/TestCellSortingTutorial.py | passing
cell_based/tutorials/TestTensileTestTutorial.py | failing
cell_based/tutorials/TestNodeBasedCellSimulationsPythonTutorial.py | failing
cell_based/TestVertexBasedCellPopulationPython.py | failing
cell_based/TestMeshBasedCellPopulationPython.py | failing
cell_based/TestNodeBasedCellPopulationPython.py | failing
cell_based/TestCaBasedCellPopulationPython.py | failing
mesh/TestPottsMeshPython.py | passing
mesh/TestChastePointPython.py | failing
core/TestFileFinderPython.py | failing
core/TestPetscToolsPython.py | failing
core/TestRandomNumberGeneratorPython.py | passing
core/TestTimerPython.py | passing
core/TestVersionPython.py | passing
core/TestOutputFileHandlerPython.py | passing

**Comment by kwabenantim** [comment]
[TestVertexBasedCellPopulationPython.py](https://github.com/kwabenantim/PyChaste/blob/master/test/python/cell_based/TestVertexBasedCellPopulationPython.py)

```
[0]PETSC ERROR: ------------------------------------------------------------------------
[0]PETSC ERROR: Caught signal number 11 SEGV: Segmentation Violation, probably memory access out of range
[0]PETSC ERROR: Try option -start_in_debugger or -on_error_attach_debugger
[0]PETSC ERROR: or see http://www.mcs.anl.gov/petsc/documentation/faq.html#valgrind
[0]PETSC ERROR: or try http://valgrind.org on GNU/linux and Apple Mac OS X to find memory corruption errors
[0]PETSC ERROR: configure using --with-debugging=yes, recompile, link, and run 
[0]PETSC ERROR: to get more information on the crash.
application called MPI_Abort(MPI_COMM_WORLD, 59) - process 0
[unset]: write_line error; fd=-1 buf=:cmd=abort exitcode=59
:
system msg for write_line failure : Bad file descriptor
```

This stems from the visualisation scene modifier: `modifier = chaste.cell_based.VtkSceneModifier2()`

**Comment by kwabenantim** [comment]
Scene rendering fixed: https://github.com/kwabenantim/PyChaste/issues/1

**Comment by kwabenantim** [comment]
Colab notebooks enabled:
https://github.com/kwabenantim/PyChaste/issues/2
https://github.com/kwabenantim/PyChaste/issues/8

**Comment by kwabenantim** [comment]
Wrappers updated to `Chaste/develop` branch:
https://github.com/kwabenantim/PyChaste/issues/7
https://github.com/kwabenantim/PyChaste/issues/13

**Comment by kwabenantim** [comment]
Fixing `c_vector` support:
https://github.com/kwabenantim/PyChaste/issues/11

**Comment by kwabenantim** [comment]
**Remaining Tasks**
- [x] Complete `c_vector` support: https://github.com/kwabenantim/PyChaste/issues/11
- [x] Fix PETSc `Vec` and `Mat` support and failing tests: https://github.com/kwabenantim/PyChaste/issues/15
- [x] Fail without crashing notebooks: https://github.com/kwabenantim/PyChaste/issues/20; https://github.com/kwabenantim/PyChaste/issues/21
- [x] Write developer documentation for adding wrappers: https://github.com/kwabenantim/PyChaste/issues/19
- [x] Move PyChaste repository to Chaste organisation: https://github.com/kwabenantim/PyChaste/issues/32

**Comment by kwabenantim** [comment]
Closing this issue as Python bindings are now implemented: https://github.com/Chaste/PyChaste. New issues will be created for further updates to the Python bindings including, but not limited to:
* Supporting new versions of dependencies
* Building conda packages for different versions of Python
* Updating the docker image
* Adding new wrappers when Chaste changes
* Adding new tutorials
* Adding new tests
